services:
  app:
    container_name: food_app_api
    restart: always
    build: .
    ports:
      - '5001:5001'
    depends_on:
      - mongodb
    links:
      - mongodb
    env_file: .env
    environment:
      - NODE_ENV=development
      - MONGODB_CON=mongodb://mongodb:27017

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
