// export * from './CustomTypes';
export * from "./IErrorResponse";
export * from "./IMessageResponse";
export * from "./IAdmin";
export * from "./ICustomer";
export * from "./IDeliveryUser";
export * from "./IFood";
export * from "./IRestaurant";
export * from "./IOffer";
export * from "./IOrder";
export * from "./ITransaction";
export * from "./IRider";
